name: Merge keiyoushi

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch: # Manual dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-merge:
    name: Merge keiyoushi
    if: github.repository == 'zosetsu-repo/zosetsu-repo.github.io'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merging
        run: |
          git remote add keiyoushi https://github.com/keiyoushi/keiyoushi.github.io
          git fetch keiyoushi
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git merge --no-edit keiyoushi/main

      - name: Push to repo
        run: |
          git push
